# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5414fe9ac58fcefc30c36973ec2b0b2a97f98f2bd6ca5e8e17d6a6e263c96fff368a215f135d9616390870b76c15969ebaf3fe6a8c6babac7be6d8094e0c7809

test:
  secret_key_base: 2af37d1cb459c8e3ece35e0f0da0cdfbfc485b56424efad2c6105260263aa901c421eab773956e48d68fa4c27374b691cd71e5073580bbc57e26f6eb987f864b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
